apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: davgus-ambulance-webapi
spec:
  parentRefs:
    - name: davgus-wac-hospital-gateway
      namespace: wac-hospital-davgus
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /davgus-api
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /api
      backendRefs:
        - group: ""
          kind: Service
          name: davgus-ambulance-webapi
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /davgus-openapi-ui
      backendRefs:
        - group: ""
          kind: Service
          name: davgus-openapi-ui
          port: 80
    - matches:
        - path:
            type: Exact
            value: /davgus-openapi
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /openapi
      backendRefs:
        - group: ""
          kind: Service
          name: davgus-ambulance-webapi
          port: 80
