apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "https://github.com/TechOctopus/davgus-ambulance-webapi//deployments/kustomize/install" # ?ref=v1.0.1
  - openapi-ui.service.yaml
  - http-route.yaml

configMapGenerator:
  - name: davgus-ambulance-webapi-mongodb-init
    behavior: replace
    files:
      - params/init-db.js
  - name: davgus-ambulance-webapi-config
    behavior: replace
    literals:
      - database=davgus-ambulance-wl
      - collection=departments

patches:
  - path: patches/ambulance-webapi.deployment.yaml

labels:
  - pairs:
      wac-fiit.github.io/component: backend
