apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: fiitkar/davgus-ambulance-ufe
    newName: fiitkar/davgus-ambulance-ufe
    newTag: 1.2.1
  - name: fiitkar/davgus-ambulance-wl-webapi
    newName: fiitkar/davgus-ambulance-wl-webapi
    newTag: 1.0.2
