apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: davgus-ambulance-webapi
  namespace: wac-hospital-davgus
spec:
  image: fiitkar/davgus-ambulance-wl-webapi
  interval: 1m0s
