apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: wac-hospital

namespace: wac-hospital-davgus

resources:
  - namespace.yaml
  - prepare.kustomization.yaml
  - cd.kustomization.yaml
  - install.kustomization.yaml
  - git-repository.yaml
  - davgus-ambulance-ufe.image-repository.yaml
  - davgus-ambulance-ufe.image-policy.yaml
  - image-update-automation.yaml
  - ambulance-webapi.image-repository.yaml
  - ambulance-webapi.image-policy.yaml
