apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: fiitkar/davgus-ambulance-ufe
    newName: fiitkar/davgus-ambulance-ufe # {"$imagepolicy":  "wac-hospital:davgus-ambulance-ufe:name"}
    newTag: main.20260323.1331 # {"$imagepolicy": "wac-hospital:davgus-ambulance-ufe:tag"}
