apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital-davgus

labels:
  - pairs:
      app.kubernetes.io/part-of: wac-hospital

resources:
  - ../../../apps/davgus-ambulance-ufe
  - ../../../apps/davgus-ambulance-webapi

patches:
  - path: patches/ambulance-webapi.service.yaml
  - path: patches/mongodb-connection.configmap.yaml
  - path: patches/mongodb.deployment.delete.yaml
  - path: patches/mongodb.service.delete.yaml
  - path: patches/mongo-pvc.delete.yaml

components:
  - ../../../components/version-developers
  - https://github.com/TechOctopus/davgus-ambulance-webapi//deployments/kustomize/components/mongodb
