apiVersion: apps/v1
kind: Deployment
metadata:
  name: davgus-ambulance-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          image: swaggerapi/swagger-ui
          env:
            - name: URL
              value: /davgus-openapi
            - name: BASE_URL
              value: /davgus-openapi-ui
