apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: davgus-ambulance-ufe-link
spec:
  microFrontend: polyfea-md-shell
  element: polyfea-md-app
  attributes:
    - name: headline
      value: Správa a umiestnenie pacientov
    - name: short-headline
      value: Správa pacientov
    - name: supporting-text
      value: |
        Systém pre správu a umiestnenie pacientov v oddeleniach nemocnice.
        Umožňuje vytvárať karty pacientov, spravovať oddelenia a priraďovať pacientov do izieb.
    - name: material-icon
      value: local_hospital
    - name: tile-img-src
      value: /davgus-ambulance-ufe/assets/card-image.png
    - name: href
      value: ./davgus-ambulance-wl
  priority: 10
  displayRules:
    - anyOf:
        - context-name: applications
        - context-name: rail-content
        - context-name: drawer-content
